name = "flyology_db"
description = "Experimental object-native transactional key-value database"
version = "0.1.0-dev"

authors = ["Yurii Rashkovskii"]
maintainers = ["Yurii Rashkovskii <yrashk@gmail.com>"]
maintainers-logins = ["yrashk"]
licenses = "MIT OR Apache-2.0"
website = "https://github.com/flyology-ada/flyology-db"
tags = ["ada", "database", "key-value", "transactions", "object-store", "spark"]
project-files = ["flyology_db.gpr"]

[[depends-on]]
flyology_object_storage = "=0.1.0-dev"

[[depends-on]]
flyology = "*"

[[depends-on]]
flyology_tla = "=0.1.0-dev"

[[depends-on]]
gnat = ">=13 & <=16.1.0"

[build-switches]
"*".ada_version = "Ada2022"
development.optimization = "Debug"
development.compile_checks = "Errors"
release.optimization = "Performance"
release.compile_checks = "Warnings"

[[actions]]
type = "test"
command = ["./tests/scripts/test.sh"]

[[pins]]
flyology_object_storage = { path='.deps/flyology-object-storage' }
