[package]
name = "flyology-db-slatedb-benchmark"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
slatedb = { path = "../../../.deps/slatedb/slatedb", version = "=0.15.0", default-features = false, features = ["aws"] }
tokio = { version = "1.47.1", features = ["macros", "rt-multi-thread"] }

[workspace]

[lints.rust]
unsafe_code = "deny"
